/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZustandTestRouteImport } from './routes/zustand-test'
import { Route as MswTestRouteImport } from './routes/msw-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicTopicIdRouteImport } from './routes/topic/$topicId'
import { Route as DemoSerializationRouteImport } from './routes/demo/serialization'
import { Route as DemoGameWorldRouteImport } from './routes/demo/game-world'

const ZustandTestRoute = ZustandTestRouteImport.update({
  id: '/zustand-test',
  path: '/zustand-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MswTestRoute = MswTestRouteImport.update({
  id: '/msw-test',
  path: '/msw-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicTopicIdRoute = TopicTopicIdRouteImport.update({
  id: '/topic/$topicId',
  path: '/topic/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSerializationRoute = DemoSerializationRouteImport.update({
  id: '/demo/serialization',
  path: '/demo/serialization',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGameWorldRoute = DemoGameWorldRouteImport.update({
  id: '/demo/game-world',
  path: '/demo/game-world',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/demo/game-world': typeof DemoGameWorldRoute
  '/demo/serialization': typeof DemoSerializationRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/demo/game-world': typeof DemoGameWorldRoute
  '/demo/serialization': typeof DemoSerializationRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/demo/game-world': typeof DemoGameWorldRoute
  '/demo/serialization': typeof DemoSerializationRoute
  '/topic/$topicId': typeof TopicTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/msw-test'
    | '/zustand-test'
    | '/demo/game-world'
    | '/demo/serialization'
    | '/topic/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/msw-test'
    | '/zustand-test'
    | '/demo/game-world'
    | '/demo/serialization'
    | '/topic/$topicId'
  id:
    | '__root__'
    | '/'
    | '/msw-test'
    | '/zustand-test'
    | '/demo/game-world'
    | '/demo/serialization'
    | '/topic/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MswTestRoute: typeof MswTestRoute
  ZustandTestRoute: typeof ZustandTestRoute
  DemoGameWorldRoute: typeof DemoGameWorldRoute
  DemoSerializationRoute: typeof DemoSerializationRoute
  TopicTopicIdRoute: typeof TopicTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zustand-test': {
      id: '/zustand-test'
      path: '/zustand-test'
      fullPath: '/zustand-test'
      preLoaderRoute: typeof ZustandTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msw-test': {
      id: '/msw-test'
      path: '/msw-test'
      fullPath: '/msw-test'
      preLoaderRoute: typeof MswTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$topicId': {
      id: '/topic/$topicId'
      path: '/topic/$topicId'
      fullPath: '/topic/$topicId'
      preLoaderRoute: typeof TopicTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/serialization': {
      id: '/demo/serialization'
      path: '/demo/serialization'
      fullPath: '/demo/serialization'
      preLoaderRoute: typeof DemoSerializationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/game-world': {
      id: '/demo/game-world'
      path: '/demo/game-world'
      fullPath: '/demo/game-world'
      preLoaderRoute: typeof DemoGameWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MswTestRoute: MswTestRoute,
  ZustandTestRoute: ZustandTestRoute,
  DemoGameWorldRoute: DemoGameWorldRoute,
  DemoSerializationRoute: DemoSerializationRoute,
  TopicTopicIdRoute: TopicTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
