/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZustandTestRouteImport } from './routes/zustand-test'
import { Route as MswTestRouteImport } from './routes/msw-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FundamentalsTopicIdRouteImport } from './routes/fundamentals/$topicId'
import { Route as DemoSerializationRouteImport } from './routes/demo/serialization'
import { Route as DemoMarioJumpRouteImport } from './routes/demo/mario-jump'
import { Route as DemoLockstepRouteImport } from './routes/demo/lockstep'
import { Route as DemoGameWorldRouteImport } from './routes/demo/game-world'
import { Route as DemoCandyCrushRouteImport } from './routes/demo/candy-crush'
import { Route as DecisionsCategoryIdRouteImport } from './routes/decisions/$categoryId'
import { Route as CasesGameIdRouteImport } from './routes/cases/$gameId'

const ZustandTestRoute = ZustandTestRouteImport.update({
  id: '/zustand-test',
  path: '/zustand-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MswTestRoute = MswTestRouteImport.update({
  id: '/msw-test',
  path: '/msw-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FundamentalsTopicIdRoute = FundamentalsTopicIdRouteImport.update({
  id: '/fundamentals/$topicId',
  path: '/fundamentals/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSerializationRoute = DemoSerializationRouteImport.update({
  id: '/demo/serialization',
  path: '/demo/serialization',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMarioJumpRoute = DemoMarioJumpRouteImport.update({
  id: '/demo/mario-jump',
  path: '/demo/mario-jump',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoLockstepRoute = DemoLockstepRouteImport.update({
  id: '/demo/lockstep',
  path: '/demo/lockstep',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGameWorldRoute = DemoGameWorldRouteImport.update({
  id: '/demo/game-world',
  path: '/demo/game-world',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoCandyCrushRoute = DemoCandyCrushRouteImport.update({
  id: '/demo/candy-crush',
  path: '/demo/candy-crush',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsCategoryIdRoute = DecisionsCategoryIdRouteImport.update({
  id: '/decisions/$categoryId',
  path: '/decisions/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesGameIdRoute = CasesGameIdRouteImport.update({
  id: '/cases/$gameId',
  path: '/cases/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/cases/$gameId': typeof CasesGameIdRoute
  '/decisions/$categoryId': typeof DecisionsCategoryIdRoute
  '/demo/candy-crush': typeof DemoCandyCrushRoute
  '/demo/game-world': typeof DemoGameWorldRoute
  '/demo/lockstep': typeof DemoLockstepRoute
  '/demo/mario-jump': typeof DemoMarioJumpRoute
  '/demo/serialization': typeof DemoSerializationRoute
  '/fundamentals/$topicId': typeof FundamentalsTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/cases/$gameId': typeof CasesGameIdRoute
  '/decisions/$categoryId': typeof DecisionsCategoryIdRoute
  '/demo/candy-crush': typeof DemoCandyCrushRoute
  '/demo/game-world': typeof DemoGameWorldRoute
  '/demo/lockstep': typeof DemoLockstepRoute
  '/demo/mario-jump': typeof DemoMarioJumpRoute
  '/demo/serialization': typeof DemoSerializationRoute
  '/fundamentals/$topicId': typeof FundamentalsTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/msw-test': typeof MswTestRoute
  '/zustand-test': typeof ZustandTestRoute
  '/cases/$gameId': typeof CasesGameIdRoute
  '/decisions/$categoryId': typeof DecisionsCategoryIdRoute
  '/demo/candy-crush': typeof DemoCandyCrushRoute
  '/demo/game-world': typeof DemoGameWorldRoute
  '/demo/lockstep': typeof DemoLockstepRoute
  '/demo/mario-jump': typeof DemoMarioJumpRoute
  '/demo/serialization': typeof DemoSerializationRoute
  '/fundamentals/$topicId': typeof FundamentalsTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/msw-test'
    | '/zustand-test'
    | '/cases/$gameId'
    | '/decisions/$categoryId'
    | '/demo/candy-crush'
    | '/demo/game-world'
    | '/demo/lockstep'
    | '/demo/mario-jump'
    | '/demo/serialization'
    | '/fundamentals/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/msw-test'
    | '/zustand-test'
    | '/cases/$gameId'
    | '/decisions/$categoryId'
    | '/demo/candy-crush'
    | '/demo/game-world'
    | '/demo/lockstep'
    | '/demo/mario-jump'
    | '/demo/serialization'
    | '/fundamentals/$topicId'
  id:
    | '__root__'
    | '/'
    | '/msw-test'
    | '/zustand-test'
    | '/cases/$gameId'
    | '/decisions/$categoryId'
    | '/demo/candy-crush'
    | '/demo/game-world'
    | '/demo/lockstep'
    | '/demo/mario-jump'
    | '/demo/serialization'
    | '/fundamentals/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MswTestRoute: typeof MswTestRoute
  ZustandTestRoute: typeof ZustandTestRoute
  CasesGameIdRoute: typeof CasesGameIdRoute
  DecisionsCategoryIdRoute: typeof DecisionsCategoryIdRoute
  DemoCandyCrushRoute: typeof DemoCandyCrushRoute
  DemoGameWorldRoute: typeof DemoGameWorldRoute
  DemoLockstepRoute: typeof DemoLockstepRoute
  DemoMarioJumpRoute: typeof DemoMarioJumpRoute
  DemoSerializationRoute: typeof DemoSerializationRoute
  FundamentalsTopicIdRoute: typeof FundamentalsTopicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zustand-test': {
      id: '/zustand-test'
      path: '/zustand-test'
      fullPath: '/zustand-test'
      preLoaderRoute: typeof ZustandTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/msw-test': {
      id: '/msw-test'
      path: '/msw-test'
      fullPath: '/msw-test'
      preLoaderRoute: typeof MswTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundamentals/$topicId': {
      id: '/fundamentals/$topicId'
      path: '/fundamentals/$topicId'
      fullPath: '/fundamentals/$topicId'
      preLoaderRoute: typeof FundamentalsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/serialization': {
      id: '/demo/serialization'
      path: '/demo/serialization'
      fullPath: '/demo/serialization'
      preLoaderRoute: typeof DemoSerializationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mario-jump': {
      id: '/demo/mario-jump'
      path: '/demo/mario-jump'
      fullPath: '/demo/mario-jump'
      preLoaderRoute: typeof DemoMarioJumpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/lockstep': {
      id: '/demo/lockstep'
      path: '/demo/lockstep'
      fullPath: '/demo/lockstep'
      preLoaderRoute: typeof DemoLockstepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/game-world': {
      id: '/demo/game-world'
      path: '/demo/game-world'
      fullPath: '/demo/game-world'
      preLoaderRoute: typeof DemoGameWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/candy-crush': {
      id: '/demo/candy-crush'
      path: '/demo/candy-crush'
      fullPath: '/demo/candy-crush'
      preLoaderRoute: typeof DemoCandyCrushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions/$categoryId': {
      id: '/decisions/$categoryId'
      path: '/decisions/$categoryId'
      fullPath: '/decisions/$categoryId'
      preLoaderRoute: typeof DecisionsCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$gameId': {
      id: '/cases/$gameId'
      path: '/cases/$gameId'
      fullPath: '/cases/$gameId'
      preLoaderRoute: typeof CasesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MswTestRoute: MswTestRoute,
  ZustandTestRoute: ZustandTestRoute,
  CasesGameIdRoute: CasesGameIdRoute,
  DecisionsCategoryIdRoute: DecisionsCategoryIdRoute,
  DemoCandyCrushRoute: DemoCandyCrushRoute,
  DemoGameWorldRoute: DemoGameWorldRoute,
  DemoLockstepRoute: DemoLockstepRoute,
  DemoMarioJumpRoute: DemoMarioJumpRoute,
  DemoSerializationRoute: DemoSerializationRoute,
  FundamentalsTopicIdRoute: FundamentalsTopicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
